remote_theme: pmarsceill/just-the-docs
#theme: "just-the-docs"
title: Matplot++
description: A C++ Graphics Library for Data Visualization 📊🗾

search_enabled: true

aux_links:
  "Matplot++ on GitHub":
    - "//github.com/alandefreitas/matplotplusplus"

footer_content: "Copyright &copy; Alan Freitas. Distributed by an <a href=\"https://github.com/alandefreitas/matplotplusplus/tree/master/LICENSE.txt\">MIT license.</a>"
